export const INIT_SHOPPING_CART_LOAD        = 'INIT_SHOPPING_CART_LOAD';
export const INIT_SHOPPING_CART_SUCCESS     = 'INIT_SHOPPING_CART_SUCCESS';
export const INIT_SHOPPING_CART_ERROR       = 'INIT_SHOPPING_CART_ERROR';

export const SHOPPING_CART_ADD_LOAD         = 'SHOPPING_CART_ADD_LOAD';
export const SHOPPING_CART_ADD_SUCCESS      = 'SHOPPING_CART_ADD_SUCCESS';
export const SHOPPING_CART_ADD_ERROR        = 'SHOPPING_CART_ADD_ERROR';

export const SHOPPING_CART_REMOVE_LOAD      = 'SHOPPING_CART_REMOVE_LOAD';
export const SHOPPING_CART_REMOVE_SUCCESS   = 'SHOPPING_CART_REMOVE_SUCCESS';
export const SHOPPING_CART_REMOVE_ERROR     = 'SHOPPING_CART_REMOVE_ERROR';

